module:
  _target_: emg2qwerty.lightning.GRUCTCModule
  in_features: 528  
  mlp_features: [384] 
  
  # --- NEW CNN Hyperparameters ---
  block_channels: [24, 24, 24, 24] # Standard from the TDSConvCTCModule
  kernel_width: 32
  # -------------------------------
  
  rnn_hidden_size: 256
  rnn_num_layers: 2
  rnn_dropout: 0.3