# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConvCTCModule
  in_features: 528          # freq * channels = (n_fft // 2 + 1) * 16 = 33 * 16
  mlp_features: [384]       # num_features = NUM_BANDS * mlp_features[-1] = 2 * 384 = 768
  block_channels: [32, 32, 32, 32]   
  kernel_width: 32
  hidden_size: 256          # BiLSTM hidden size per direction 
  num_lstm_layers: 2
  lstm_dropout: 0.3

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
